apiVersion: 1

datasources:
  - name: gravelled
    uid: gravelled-pg
    type: postgres
    access: proxy
    url: $GRAVELLED_DB_HOST
    user: $GRAVELLED_DB_USER
    isDefault: true
    editable: true
    jsonData:
      database: $GRAVELLED_DB_NAME
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: $GRAVELLED_DB_PASSWORD
